### ISSUE TITLE
Getting Problem when taking screenshot

### ISSUE THREAD

**Issue by nitinsinghthink** [voxeet/voxeet-sdk-android-gettingstarted#15]
When i am trying to take screenshot/snapshot while connecting in room with enabled Video camera, I am only getting black screen 
![image](https://user-images.githubusercontent.com/81210488/154901511-8fa0cb79-5dd8-46c5-9ffd-1b056c78e35a.png)
.
Can anyone help me on this

**Comment by FabienLavocat** [comment]
Duplicate of #16
