### ISSUE TITLE
Getting Problem while taking an Screenshot/Snapshot

### ISSUE THREAD

**Issue by nitinsinghthink** [voxeet/voxeet-sdk-android-gettingstarted#16]
When i am trying to take screenshot/snapshot while connecting in room with enabled Video camera, I am only getting black screen as attached in the below images @codlab @FabienLavocat 
![154901511-8fa0cb79-5dd8-46c5-9ffd-1b056c78e35a](https://user-images.githubusercontent.com/81210488/158101501-38a90667-7986-4c0e-82d5-77132394b93f.png)
Can anyone help me in this..

**Comment by FabienLavocat** [comment]
Hi @nitinsinghthink
I do not have that issue with an application running on my phone. Are you testing the screenshot on the emulator?
Could you please share a code sample that I can run on a device and test myself?

Thanks,
Fabien

**Comment by nitinsinghthink** [comment]
@FabienLavocat Thanks for reply! I am testing this on Mobile devices not on emulator.
In class VoxeetActionBarView i have used following code to capture screenshot/snapshot while video calling .

View v1 = context.getWindow().getDecorView().getRootView();
            v1.setDrawingCacheEnabled(true);
            Bitmap bitmap = Bitmap.createBitmap(v1.getDrawingCache());
            v1.setDrawingCacheEnabled(false);
            
I have also tried with this library     implementation 'com.jraska:falcon:2.2.0'
Code:-
 Bitmap bitmap = Falcon.takeScreenshotBitmap(AppController.getCurrentActivity());
 
 But we are unable to get video screen i am only getting blank screen .
 Note:- During taking an screenshot/snapshot my video camera is enabled.

**Comment by FabienLavocat** [comment]
The `getDrawingCache()` function won't work (and is deprecated) because of the way the VideoView element are drawn on the screen. Instead you should use [PixelCopy](https://developer.android.com/reference/android/view/PixelCopy).
Check out this blog post: https://betterprogramming.pub/how-to-capture-in-app-screenshots-in-android-567548eb78a2

**Comment by codlab** [comment]
The TextureView used contains its own gl context which does not expose the Surface nor the SurfaceView and won't let the bitmap to be fetched directly. However the VideoView gives access to 

```
@Nullable
public Bitmap getBitmap();

@Nullable
public Bitmap getBitmap(@NonNull Bitmap bitmap);

@Nullable
public Bitmap getBitmap(int width, int height);
```

Where the preferable call is the getBitmap(Bitmap)

**Comment by nitinsinghthink** [comment]
@codlab Can you elaborate more about this?

**Comment by nitinsinghthink** [comment]
@FabienLavocat Thanks . Working with Pixelcopy.
