### ISSUE TITLE
Dolby Group Video call

### ISSUE THREAD

**Issue by qamarkhan2166** [voxeet/voxeet-sdk-android-gettingstarted#21]
**Hey Dev :**
I am using this code between 1 to 1 video call which works fine but i want to know how we can handle group video call For example 4 participant wants to make a call between them and all users can see each other videos .
last thing i want to know how many members dolby allow in a group call if sdk supports.

 `val isLocal = user.id == VoxeetSDK.session().participantId
            val stream = user.streamsHandler().getFirst(MediaStreamType.Camera)
            val video: VideoView =
                if (isLocal) myVideo else otherVideo`

**Comment by FabienLavocat** [comment]
If you want to create a group call, you can leverage the same code base, the only logic that you need to change is how you display the video tiles. In this example we only have the local video and the remote participant. Instead, make the ui dynamic to display as many video tiles as you have participants.

This is where we display the remote video: https://github.com/dolbyio-samples/comms-sdk-android-getting-started/blob/master/app/src/main/res/layout/activity_main.xml#L124
Instead, make this section dynamic and build your video element as you have participants coming into the conference.
This section - https://github.com/dolbyio-samples/comms-sdk-android-getting-started/blob/master/app/src/main/java/com/example/myapplication/MainActivity.java#L409 - is where we decide what video UI element to use. Instead, add a new video element if there is a new participant coming in.

In a group call, we allow 50 participants to join a conference if the video is on, or 250 participants for Audio Only conferences. On a mobile application, you can display up to 4 video tiles out of the 50 participants. Check out our documentation regarding the [Conference Capacity](https://docs.dolby.io/communications-apis/docs/guides-conference-capacity).

**Comment by qamarkhanInnovo** [comment]
Hey Fabien 

First of all thanks for your reply highly appreciate you. I understand and struggling to dynamically attach third and 4th participant videoView . 
Let suppose we add 4 video views in a layout and we want to see third and 4th participant video when they join a call but i am struggling to modify this code for 3rd and 4th participant

            boolean isLocal = user.getId().equals(VoxeetSDK.session().getParticipantId());
            MediaStream stream = user.streamsHandler().getFirst(MediaStreamType.Camera);
            VideoView video = isLocal ? this.binding.video : this.binding.videoOther;
            
            could you please help me out how to attach video view for 3rd and 4th participant. Please share a code sample
            Thanks @FabienLavocat

**Comment by FabienLavocat** [comment]
First create 4 video elements in your UI:
```xml
        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="300dp">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.voxeet.sdk.views.VideoView
                    android:id="@+id/videoLocal"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.voxeet.sdk.views.VideoView
                    android:id="@+id/videoFirst"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </LinearLayout>
        </LinearLayout>

        <LinearLayout
            android:layout_width="match_parent"
            android:layout_height="300dp">

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.voxeet.sdk.views.VideoView
                    android:id="@+id/videoSecond"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </LinearLayout>

            <LinearLayout
                android:layout_width="0dp"
                android:layout_height="match_parent"
                android:layout_weight="1">

                <com.voxeet.sdk.views.VideoView
                    android:id="@+id/videoThird"
                    android:layout_width="match_parent"
                    android:layout_height="match_parent" />
            </LinearLayout>
        </LinearLayout>
```

I would then create a function to get the video element
```java
private VideoView getVideoElement(Participant user) {
    if (user.getId().equals(VoxeetSDK.session().getParticipantId())) {
        return this.binding.videoLocal;
    }

    if (!this.binding.videoFirst.isAttached()) {
        return this.binding.videoFirst;
    }

    if (!this.binding.videoSecond.isAttached()) {
        return this.binding.videoSecond;
    }

    if (!this.binding.videoThird.isAttached()) {
        return this.binding.videoThird;
    }

    return null;
}
```

And replace this code (several occurrences in the file):

```java
boolean isLocal = user.getId().equals(VoxeetSDK.session().getParticipantId());
VideoView video = isLocal ? this.binding.video : this.binding.videoOther;
```
by
```java
VideoView video = getVideoElement(user);
```

_Note: this is a quick and dirty code, please make sure to clean it up before using it._

**Comment by qamarkhanInnovo** [comment]
Hey @FabienLavocat 

I am implementing as you mentioned above ^^, but getVideoElement(user) function not working fine for remote participant users.
it randomly assign video to any other VideoView on receiver end. i am checking the logs but couldn,t get success because it changed rapidly.
Even its not working fine between 2 participants instead of 3 or 4 participant. could you please check one more time getVideoElement(user) function. 
thanks


```
fun updateStreams(myVideo: VideoView, videoFirst: VideoView, videoSecond: VideoView, videoThird: VideoView) {
        val participantSize = VoxeetSDK.conference().participants.size
        handleJoinCallParticipantsVideoViews(participantSize, videoSecond, videoThird)
        for (user in VoxeetSDK.conference().participants) {
            val stream = user.streamsHandler().getFirst(MediaStreamType.Camera)
            val video: VideoView? = getVideoElement(user, myVideo, videoFirst, videoSecond, videoThird)
         
            if (null != stream && stream.videoTracks().isNotEmpty()) {
                handleRequestBetweenVoiceAndVideo(true)
                video!!.visibility = VISIBLE
                video.attach(user.id!!, stream)
            }
        }
    }

    private fun getVideoElement(user: Participant, myVideo: VideoView, videoFirst: VideoView, videoSecond: VideoView, videoThird: VideoView): VideoView? {
        if (user.id == VoxeetSDK.session().participantId) {
            return myVideo
        }
        if (!videoFirst.isAttached) {
            return videoFirst
        }
        if (!videoSecond.isAttached) {
            return videoSecond
        }
        if (!videoThird.isAttached) {
            return videoThird
        }
        return null
    }
```

**Comment by FabienLavocat** [comment]
The code that I was provided was simply a basic example that you could use to start. I've added a bit of logic, build upon this code (this code might not fully work):
```java
private VideoView getVideoElement(Participant user) {
    if (user.getId().equals(VoxeetSDK.session().getParticipantId())) {
        return this.binding.videoLocal;
    }

    if (!this.binding.videoFirst.isAttached() || this.binding.videoFirst.getPeerId() == user.getId()) {
        return this.binding.videoFirst;
    }

    if (!this.binding.videoSecond.isAttached() || this.binding.videoSecond.getPeerId() == user.getId()) {
        return this.binding.videoSecond;
    }

    if (!this.binding.videoThird.isAttached() || this.binding.videoThird.getPeerId() == user.getId()) {
        return this.binding.videoThird;
    }

    return null;
}
```

**Comment by qamarkhanInnovo** [comment]
> The code that I was provided was simply a basic example that you could use to start. I've added a bit of logic, build upon this code (this code might not fully work):
> 
> ```java
> private VideoView getVideoElement(Participant user) {
>     if (user.getId().equals(VoxeetSDK.session().getParticipantId())) {
>         return this.binding.videoLocal;
>     }
> 
>     if (!this.binding.videoFirst.isAttached() || this.binding.videoFirst.getPeerId() == user.getId()) {
>         return this.binding.videoFirst;
>     }
> 
>     if (!this.binding.videoSecond.isAttached() || this.binding.videoSecond.getPeerId() == user.getId()) {
>         return this.binding.videoSecond;
>     }
> 
>     if (!this.binding.videoThird.isAttached() || this.binding.videoThird.getPeerId() == user.getId()) {
>         return this.binding.videoThird;
>     }
> 
>     return null;
> }
> ```

Hey @FabienLavocat  This solution is much better than previous one but yes you are right, its not fully work .
for 2 participants is fine but there is lack while attach 3rd and 4th participants . sometime fine but some time not .
when third user enable or disable camera it cause lack to attach and deAttach video.
can you please share me advance topic reference of video call handling because i check and found simple one .
Thanks

**Comment by FabienLavocat** [comment]
This is the complete code that works:
```java
Hashtable<String, VideoView> participantVideos = new Hashtable<String, VideoView>();

private VideoView getVideoElement(Participant user) {
    if (user.getId().equals(VoxeetSDK.session().getParticipantId())) {
        return this.binding.videoLocal;
    }

    if (!this.binding.videoFirst.isAttached() || this.binding.videoFirst.getPeerId() == user.getId()) {
        return this.binding.videoFirst;
    }

    if (!this.binding.videoSecond.isAttached() || this.binding.videoSecond.getPeerId() == user.getId()) {
        return this.binding.videoSecond;
    }

    if (!this.binding.videoThird.isAttached() || this.binding.videoThird.getPeerId() == user.getId()) {
        return this.binding.videoThird;
    }

    return null;
}

private void updateStreams() {
    for (Participant user : VoxeetSDK.conference().getParticipants()) {
        MediaStream stream = user.streamsHandler().getFirst(MediaStreamType.Camera);

        if (stream == null || stream.videoTracks().isEmpty()) {
            // Remove the entry from the dictionary and release the video element
            VideoView videoElement = participantVideos.remove(user.getId());
            if (videoElement != null) {
                videoElement.unAttach();
                videoElement.setVisibility(View.INVISIBLE);
            }
            continue;
        }

        if (!participantVideos.containsKey(user.getId())) {
            // Get an empty video element
            VideoView videoElement = getVideoElement(user);
            if (videoElement == null) continue;

            // Add the video element to the dictionary
            participantVideos.put(user.getId(), videoElement);
        }

        VideoView videoView = participantVideos.get(user.getId());

        // Display the stream on the UI
        videoView.setVisibility(View.VISIBLE);
        videoView.attach(user.getId(), stream);
    }
}
```

**Comment by qamarkhanInnovo** [comment]
Thank you so much @FabienLavocat appreciate your support and help bro. it works fine now .
