### ISSUE TITLE
Sample app crash

### ISSUE THREAD

**Issue by josechagas** [voxeet/voxeet-sdk-android-gettingstarted#3]
**When executing this sample app, it crashes with the error:**

`java.lang.NoSuchMethodError: No static method create(Lorg/webrtc/EglBase$Context;[I)Lorg/webrtc/EglBase; in class Lorg/webrtc/EglBase; or its super classes (declaration of 'org.webrtc.EglBase' appears in /data/app/com.example.myapplication-1/base.apk)
        at org.webrtc.SafeRenderFrameEglRenderer$2.call(SafeRenderFrameEglRenderer.java:229)
        at org.webrtc.SafeRenderFrameEglRenderer$2.call(SafeRenderFrameEglRenderer.java:217)
        at org.webrtc.ThreadUtils$3.run(ThreadUtils.java:173)
        at android.os.Handler.handleCallback(Handler.java:739)
        at android.os.Handler.dispatchMessage(Handler.java:95)
        at android.os.Looper.loop(Looper.java:148)
        at android.os.HandlerThread.run(HandlerThread.java:61)
`

### **How to reproduce:**
**Steps:**

- IDE: Android Studio 3.6.3

1. Type user session.
2. Press login button.
3. Wait until Toast with success appear.
4. Type conference name.
5. Press start button.
6. Now the app crashes, but if it does not happen, go to step 7.
7. Press start video button.
8. The app crashes.

**Devices tested:**
- Galaxy J2 Prime Android version: 6.0.1
- Moto G5 Plus Android version: 8.1.0

### OBS:
I followed the steps presented at this link [https://www.voxeet.com/documentation/sdk/samples/basic-audio-conference](url) created my own sample app and this **error** happen to.

**My app version gradle**

android {
    compileSdkVersion 29
    buildToolsVersion "29.0.2"

    defaultConfig {
        applicationId "br.eti.nucleus.voxeettestsdk"
        minSdkVersion 21
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jdk7:$kotlin_version"
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.core:core-ktx:1.2.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

    implementation ("com.voxeet.sdk:public-sdk:2.2.0") {
        transitive = true
    }
}

**Comment by FabienLavocat** [comment]
Please check the latest version of the sample app. If the issue still happens, please reopen.
