### ISSUE TITLE
Screen Sharing works on Sample App but not when implemented

### ISSUE THREAD

**Issue by TS-0703** [voxeet/voxeet-sdk-android-gettingstarted#8]
The entire app works fine when implemented except for the screen sharing. When running the **sample** app on my device however the screen sharing works, but when I run my implemented version, it sends me the prompt for Screen sharing and once I tap "Start Now" nothing happens. There were no major code edits on my end, mostly cosmetic edits and change of Activity name.

**Comment by FabienLavocat** [comment]
@184726W by "nothing happens", do you mean that the other participants do not receive the video stream from the screen share?

**Comment by TS-0703** [comment]
@FabienLavocat More like the streaming function doesn't run after the android prompt is accepted.

**Comment by FabienLavocat** [comment]
@184726W What version of the Android OS are you targeting? What version of the Voxeet SDK are you using?

**Comment by TS-0703** [comment]
@FabienLavocat we were running the code on Android 10 devices and using Voxeet SDK version 3.0.0

**Comment by FabienLavocat** [comment]
What's your targetSdkVersion?
https://github.com/voxeet/voxeet-sdk-android-gettingstarted/blob/master/app/build.gradle#L9

**Comment by TS-0703** [comment]
The targetSdkVersion is 29. Apologies for any confusion, still very new to Android Development.

**Comment by FabienLavocat** [comment]
No worries!
So Android 10 (API 29+) has introduced a new service for screensharing. I would recommend to either target the SDK 28 or upgrade to our latest 3.1 SDK

**Comment by FabienLavocat** [comment]
Hi @184726W, I think we found a problem with the screenshare in the sample app with the latest SDK, please check the PR #10 to find what needs to be updated. Let me know if you still have an issue after this change.

**Comment by TS-0703** [comment]
Hello, @FabienLavocat I've just tested the fix, happy to report that it's working! Thanks for all the help and prompt responses!
